"use strict";
exports.__esModule = true;
var account_1 = require("./account");
var actions_1 = require("./actions");
var volumes_1 = require("./volumes");
var volumesActions_1 = require("./volumesActions");
var certificates_1 = require("./certificates");
var domains_1 = require("./domains");
var domainRecords_1 = require("./domainRecords");
var droplets_1 = require("./droplets");
var dropletActions_1 = require("./dropletActions");
var floatingIps_1 = require("./floatingIps");
var floatingIpActions_1 = require("./floatingIpActions");
var regions_1 = require("./regions");
var sizes_1 = require("./sizes");
var firewalls_1 = require("./firewalls");
var images_1 = require("./images");
var imageActions_1 = require("./imageActions");
var loadBalancers_1 = require("./loadBalancers");
var snapshots_1 = require("./snapshots");
var sshKeys_1 = require("./sshKeys");
var tags_1 = require("./tags");
var DigitalOcean = /** @class */ (function () {
    function DigitalOcean(oauthClient) {
        this.oauthClient = oauthClient;
        this.account = new account_1["default"](this.oauthClient);
        this.actions = new actions_1["default"](this.oauthClient);
        this.volumes = new volumes_1["default"](this.oauthClient);
        this.volumesActions = new volumesActions_1["default"](this.oauthClient);
        this.certificates = new certificates_1["default"](this.oauthClient);
        this.domains = new domains_1["default"](this.oauthClient);
        this.domainRecords = new domainRecords_1["default"](this.oauthClient);
        this.droplets = new droplets_1["default"](this.oauthClient);
        this.dropletActions = new dropletActions_1["default"](this.oauthClient);
        this.floatingIps = new floatingIps_1["default"](this.oauthClient);
        this.floatingIpActions = new floatingIpActions_1["default"](this.oauthClient);
        this.firewalls = new firewalls_1["default"](this.oauthClient);
        this.images = new images_1["default"](this.oauthClient);
        this.imageActions = new imageActions_1["default"](this.oauthClient);
        this.loadBalancers = new loadBalancers_1["default"](this.oauthClient);
        this.regions = new regions_1["default"](this.oauthClient);
        this.sizes = new sizes_1["default"](this.oauthClient);
        this.snapshots = new snapshots_1["default"](this.oauthClient);
        this.sshKeys = new sshKeys_1["default"](this.oauthClient);
        this.tags = new tags_1["default"](this.oauthClient);
    }
    return DigitalOcean;
}());
exports["default"] = DigitalOcean;
